### ISSUE TITLE
make a navbar

### ISSUE THREAD

**Issue by DrakeMorrison** [nss-evening-cohort-7/bandz-social-lubricant#1]
# Story
As a user, I need a way to easily navigate between pages. 

# Acceptance Criteria
**When** The user clicks a link on the navbar
**Then** They are taken to the correct page
**And** They see the page they are on highlited

# Technical Notes
- Create a nav bar that has 4 links and a logo on it
- Make sure the links work on all pages

**Comment by BLRussell-09** [comment]
![home](https://user-images.githubusercontent.com/14021906/37318486-bf3cfff2-2638-11e8-86ef-5fc752dbc82a.png)
