### ISSUE TITLE
insert band history text

### ISSUE THREAD

**Issue by Coreylutrick** [nss-evening-cohort-7/bandz-social-lubricant#10]
# Story
User sees the Band History content @ index.html page

# Acceptance Criteria
**When** User lands on the homepage
**Then** User will see the Band History Content

# Technical Notes
- use HTML, CSS
-

**Comment by BLRussell-09** [comment]
![home](https://user-images.githubusercontent.com/14021906/37318550-1aa56348-2639-11e8-8df4-c48c3b95652b.png)
