### ISSUE TITLE
write album image array

### ISSUE THREAD

**Issue by DrakeMorrison** [nss-evening-cohort-7/bandz-social-lubricant#13]

**Comment by BLRussell-09** [comment]
Story
  "As a user I want to see a list of the albums that my favorite band has made"
Acceptance Criteria:
  Album images are compiled in an array
Technical Notes:
  Create an array of images for the album cover
![album](https://user-images.githubusercontent.com/14021906/37318796-647c386a-263a-11e8-8942-f5f272d7231c.png)
