### ISSUE TITLE
make a footer

### ISSUE THREAD

**Issue by Coreylutrick** [nss-evening-cohort-7/bandz-social-lubricant#14]

**Comment by BLRussell-09** [comment]
Story:
  "As a user, i would like to see some information on each page about the creators"
Acceptance Criteria:
  **When**

  1. The user loads a page
 
 **Then**

  1. The page loads with a footer

Technical Notes:
  Make a footer with the site creators names.
![home](https://user-images.githubusercontent.com/14021906/37318986-2293825e-263b-11e8-82d9-1afe4602ea7f.png)
