### ISSUE TITLE
write album data

### ISSUE THREAD

**Issue by DrakeMorrison** [nss-evening-cohort-7/bandz-social-lubricant#15]

**Comment by BLRussell-09** [comment]
**Story**:
  "As a user I need to see information about each album once I have clicked on the album"
**Acceptance Criteria**
  Create an array of objects containing the song  name and the duration of each
** Technical Notes**
  Create a variable that contains an array of objects
- var albums = [
  {
    name: albumName
    songs: ['song1', 'song2', 'song3']
    duration: ['3:02']
  }
];
