### ISSUE TITLE
Make Merch Page

### ISSUE THREAD

**Issue by DrakeMorrison** [nss-evening-cohort-7/bandz-social-lubricant#6]
# Story
When user navigates to merch page, they should see a list of merchandise for sale

# Acceptance Criteria
**When** user loads the page
**Then** they should see images of merch

# Technical Notes
- Create merchCard function
- create merch.html

**Comment by Junochop** [comment]
https://nashvillesoftware.slack.com/files/U8Y9X43PH/F9NT9DESZ/merchandise.png

**Comment by Junochop** [comment]
good
