### ISSUE TITLE
make albums page

### ISSUE THREAD

**Issue by Coreylutrick** [nss-evening-cohort-7/bandz-social-lubricant#7]
# Story
When user loads page they should see a list of albums.

# Acceptance Criteria
**When** user loads page there should be a series of albums showing
**Then** when user clicks on album, they should be taken to new page with more info about album.

# Technical Notes
- create albums.html
- create song html pages

**Comment by BLRussell-09** [comment]
![album](https://user-images.githubusercontent.com/14021906/37318528-029476c2-2639-11e8-8214-d0a21da7660f.png)

**Comment by BLRussell-09** [comment]
![tracklist](https://user-images.githubusercontent.com/14021906/37318581-43e1c440-2639-11e8-98a4-9e85f1269c8e.png)
