### ISSUE TITLE
merch data

### ISSUE THREAD

**Issue by DrakeMorrison** [nss-evening-cohort-7/bandz-social-lubricant#9]
# Story
  User is able to see all merchandise items @Merchant Page   

# Acceptance Criteria
``` 
var merchandise = [
img1, img2, img3, img4, img5, img6, img7, img8, img9
] ;
```

# Technical Notes
-Data Array will live@ Main.JS

**Comment by BLRussell-09** [comment]
![merchandise](https://user-images.githubusercontent.com/14021906/37318573-37ff0e62-2639-11e8-8f27-91f03aac4772.png)
